/**
 * Church of Christ Union Church - Wing and Event Definitions
 */

export const DEFAULT_WINGS = [
  {
    id: 'general-church',
    name: 'General Church',
    slug: 'general-church',
    tagline: 'The heart of our congregational worship and community life',
    description: 'Encompasses main Sunday worship services, special prayer conventions, Bible studies, and church-wide fellowship events.',
    icon: 'Globe',
    accentColor: '#800000',
    secondaryColor: '#a31f1f',
    gradient: 'from-red-900 via-rose-900 to-red-800',
    bgGlow: 'rgba(128, 0, 0, 0.18)',
    badge: 'Congregational',
    order: 1,
  },
  {
    id: 'ce-union',
    name: 'Christian Endeavour (CE Union)',
    slug: 'ce-union',
    tagline: 'Fostering fellowship, discipleship, and service for teenagers and young people',
    description: "A historic young people's movement dedicated to nurturing active spiritual growth, missions, and leadership skills.",
    icon: 'Sparkles',
    accentColor: '#800000',
    secondaryColor: '#a31f1f',
    gradient: 'from-red-900 via-rose-900 to-red-800',
    bgGlow: 'rgba(128, 0, 0, 0.15)',
    badge: 'Fellowship & Discipleship',
    order: 2,
  },
  {
    id: 'womens-fellowship',
    name: "Women's Fellowship (Mahila Samiti)",
    slug: 'womens-fellowship',
    tagline: 'Encouraging women through intercessory prayer and compassionate service',
    description: 'Bringing together the women of the congregation for weekly cottage prayers, fasting prayers, and charitable outreach initiatives.',
    icon: 'HeartHandshake',
    accentColor: '#800000',
    secondaryColor: '#a31f1f',
    gradient: 'from-red-900 via-rose-900 to-red-800',
    bgGlow: 'rgba(128, 0, 0, 0.15)',
    badge: 'Prayer & Service',
    order: 3,
  },
  {
    id: 'sunday-school',
    name: 'Sunday School',
    slug: 'sunday-school',
    tagline: "Nurturing children in the knowledge of God's Word",
    description: 'Dedicated to teaching biblical truths, moral values, and gospel action songs to children from toddler to high school age.',
    icon: 'BookOpen',
    accentColor: '#800000',
    secondaryColor: '#a31f1f',
    gradient: 'from-red-900 via-rose-900 to-red-800',
    bgGlow: 'rgba(128, 0, 0, 0.15)',
    badge: 'Children Ministry',
    order: 4,
  },
  {
    id: 'youth-fellowship',
    name: 'Youth Fellowship',
    slug: 'youth-fellowship',
    tagline: 'Uniting and equipping the youth for Christ',
    description: 'A dynamic gathering of youth for praise, Bible studies, community outreach, and sports fellowship.',
    icon: 'Trophy',
    accentColor: '#800000',
    secondaryColor: '#a31f1f',
    gradient: 'from-red-900 via-rose-900 to-red-800',
    bgGlow: 'rgba(128, 0, 0, 0.15)',
    badge: 'Dynamic & Active',
    order: 5,
  },
  {
    id: 'elders-fellowship',
    name: "Elder's Fellowship",
    slug: 'elders-fellowship',
    tagline: 'Sharing wisdom, prayer, and supportive fellowship in the golden years',
    description: 'A fellowship for seniors and elders of the church focusing on pastoral visits, prayer support, and community care.',
    icon: 'Palette',
    accentColor: '#800000',
    secondaryColor: '#a31f1f',
    gradient: 'from-red-900 via-rose-900 to-red-800',
    bgGlow: 'rgba(128, 0, 0, 0.15)',
    badge: 'Wisdom & Care',
    order: 6,
  }
];
